export default {
  REQ_USER_REGISTER: 'REQ_USER_REGISTER',
  RECV_USER_REGISTRATION: 'RECV_USER_REGISTRATION',
  REQ_USER_LOGIN: 'REQ_USER_LOGIN',
  RECV_USER_LOGIN: 'RECV_USER_LOGIN',
  TOKEN_REQUEST: 'TOKEN_REQUEST',
  USER_AUTH: 'USER_AUTH',
  REQ_LOGOUT: 'REQ_LOGOUT',
  RECV_ERROR: 'RECV_ERROR',
};
