export default {
  RECALCULATE: 'RECALCULATE',
  ADD_TO_CART: 'ADD_TO_CART',
  ADDED_TO_CART: 'ADDED_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  GET_CART: 'GET_CART',
  RECV_CART: 'RECV_CART',
};
