export const REQ_USER_REGISTER = 'REQ_USER_REGISTER';
export const RECV_USER_REGISTRATION = 'RECV_USER_REGISTRATION';
export const REQ_USER_LOGIN = 'REQ_USER_LOGIN';
export const RECV_USER_LOGIN = 'RECV_USER_LOGIN';
export const TOKEN_REQUEST = 'TOKEN_REQUEST';
export const USER_AUTH = 'USER_AUTH';
export const REQ_LOGOUT = 'REQ_LOGOUT';
export const RECV_ERROR = 'RECV_ERROR';
